// 스크립트 이름: CommentBible 관리자 인사이트 무네트워크 테스트
// 버전: 1.0.0
// 작성일: 2026-08-14
// 변경사항: dedupe/retry/offline/RLS/export/XSS/retention/10k 검증
// 용도: candidate 자동 회귀
// 사용자 입력 필요: 없음
import test from 'node:test';import assert from 'node:assert/strict';import {AnalyticsStore,BoundedOutbox,MAX_OUTBOX,newEvent,rotateIdentity,csvCell,escapeHtml} from '../candidate/admin-insights/runtime.mjs';
const admin={verifiedUserId:'admin-1'},user={verifiedUserId:'user-1'};

test('중복·순서 변경·재시도는 event_id로 한 번만 반영된다',()=>{const store=new AnalyticsStore({admins:['admin-1']}),a=newEvent('page_view',{occurred_at:'2026-08-14T01:00:02Z'}),b=newEvent('comment_created',{occurred_at:'2026-08-14T01:00:01Z'});assert.deepEqual(store.ingest([a,b],new Date('2026-08-14T01:00:03Z')),{accepted:2,duplicate:0,rejected:0});assert.deepEqual(store.ingest([b,a],new Date('2026-08-14T01:00:04Z')),{accepted:0,duplicate:2,rejected:0});assert.equal(store.events.size,2)});
test('오프라인 outbox는 bounded이고 복귀 재시도 후에만 제거된다',async()=>{let online=false;const box=new BoundedOutbox(async()=>({ok:online}));for(let i=0;i<MAX_OUTBOX+9;i++)box.push(newEvent('page_view'));assert.equal(box.queue.length,MAX_OUTBOX);assert.equal(box.dropped,9);assert.equal((await box.flush()).sent,0);online=true;assert.equal((await box.flush()).sent,20);assert.equal(box.queue.length,MAX_OUTBOX-20)});
test('visitor 30일, session 30분·일 경계 rotation',()=>{const t=Date.parse('2026-08-14T10:00:00Z'),a=rotateIdentity(null,t),b=rotateIdentity(a,t+10*60_000),c=rotateIdentity(b,t+41*60_000),d=rotateIdentity(c,t+31*86400_000);assert.equal(a.visitorId,b.visitorId);assert.equal(a.sessionId,b.sessionId);assert.notEqual(b.sessionId,c.sessionId);assert.notEqual(c.visitorId,d.visitorId)});
test('RLS/ACL matrix는 익명·일반·client role claim을 거부한다',()=>{const store=new AnalyticsStore({admins:['admin-1']});store.ingest([newEvent('page_view')]);assert.throws(()=>store.queryVisitors(null),/forbidden/);assert.throws(()=>store.queryVisitors(user),/forbidden/);assert.throws(()=>store.queryVisitors({verifiedUserId:'user-1',app_metadata:{role:'admin'}}),/forbidden/);assert.equal(store.queryVisitors(admin).rows.length,1)});
test('민감정보 키·원문 경로 query를 보존하지 않는다',()=>{const store=new AnalyticsStore({admins:['admin-1']});const bad=newEvent('comment_created',{properties:{comment:'secret text'}}),good=newEvent('page_view',{path:'/read?token=secret',properties:{page_kind:'reader'}});const result=store.ingest([bad,good]);assert.equal(result.rejected,1);const saved=[...store.events.values()][0];assert.equal(saved.path,'/read');assert.ok(!JSON.stringify(saved).includes('secret'))});
test('CSV formula injection과 XSS payload를 무력화한다',()=>{for(const value of ['=1+1','+SUM(A1:A2)','-2+3','@cmd','\tformula'])assert.ok(csvCell(value).startsWith("'"));assert.equal(escapeHtml('<img src=x onerror=alert(1)>'),'&lt;img src=x onerror=alert(1)&gt;')});
test('개인정보 철회는 연결 이벤트 삭제와 replay tombstone을 수행한다',()=>{const store=new AnalyticsStore({admins:['admin-1']}),visitor=crypto.randomUUID(),event=newEvent('page_view',{visitor_id:visitor});store.ingest([event]);store.withdraw(visitor);assert.equal(store.events.size,0);assert.equal(store.ingest([{...event,event_id:crypto.randomUUID()}]).rejected,1)});
test('30일 raw retention은 일별 rollup 후 원시행을 제거한다',()=>{const store=new AnalyticsStore(),old=newEvent('page_view',{occurred_at:'2026-06-01T00:00:00Z'}),recent=newEvent('page_view',{occurred_at:'2026-08-13T00:00:00Z'});store.ingest([old],new Date('2026-06-01T00:00:01Z'));store.ingest([recent],new Date('2026-08-13T00:00:01Z'));store.rollupAndRetain(new Date('2026-08-14T00:00:00Z'));assert.equal(store.events.size,1);assert.equal(store.rollups.get('2026-06-01:page_view').count,1)});
test('cursor 페이지네이션은 중복·누락 없이 최대 limit을 지킨다',()=>{const store=new AnalyticsStore({admins:['admin-1']});for(let i=0;i<61;i++)store.ingest([newEvent('page_view',{session_id:crypto.randomUUID(),occurred_at:new Date(Date.parse('2026-08-14T00:00:00Z')+i*1000).toISOString()})],new Date('2026-08-14T01:00:00Z'));const a=store.queryVisitors(admin,{limit:25}),b=store.queryVisitors(admin,{limit:25,cursor:a.next_cursor}),c=store.queryVisitors(admin,{limit:25,cursor:b.next_cursor}),ids=[...a.rows,...b.rows,...c.rows].map(x=>x.session_id);assert.equal(ids.length,61);assert.equal(new Set(ids).size,61)});
test('10k/50k analytics load model은 batch·connection/storage 병목을 수치화한다',()=>{const model=users=>{const avgEvents=users*.0025,peakEvents=users*.035,batchFill=12,peakRequests=peakEvents/batchFill,connections=peakRequests*.08,raw30d=avgEvents*86400*30,rowBytes=420,indexFactor=1.8;return{users,avgEvents,peakEvents,peakRequests,connections,storageGb:raw30d*rowBytes*indexFactor/1e9}};const ten=model(10000),fifty=model(50000);assert.ok(Math.abs(ten.peakEvents-350)<1e-9);assert.ok(ten.peakRequests<30&&ten.connections<3);assert.ok(ten.storageGb<50);assert.ok(Math.abs(fifty.peakEvents-1750)<1e-9&&fifty.storageGb>100)});
// 스크립트 끝 — CommentBible 관리자 인사이트 무네트워크 테스트 1.0.0
