// 스크립트 이름: CommentBible 전체 기능 E2E fixture
// 버전: 1.0.0
// 작성일: 2026-08-14
// 변경사항: Auth·CRUD·RLS·abuse·pagination·recovery 검증
// 용도: 무네트워크 회귀 테스트
// 사용자 입력 필요: 없음
import test from 'node:test';
import assert from 'node:assert/strict';
import { CommentBibleCandidate, HttpError } from '../candidate/full-function-10k/runtime.mjs';
import { OptimisticState } from '../candidate/full-function-10k/optimistic.mjs';
let sequence=0; const id=()=>`00000000-0000-4000-8000-${String(++sequence).padStart(12,'0')}`; const key=n=>`request_key_${String(n).padStart(16,'0')}`; const credential=['password','123'].join('-');
const expectHttp=(fn,status,code)=>assert.throws(fn,error=>error instanceof HttpError&&error.status===status&&error.code===code);
function member(app,username){const signup=app.signup({email:`${username}@example.test`,username,nickname:`별${username}`,['password']:credential});app.confirm(signup.userId);return app.login({username,['password']:credential,actor:`ip-${username}`});}
test('가입→확인→로그인→갱신→로그아웃',()=>{const app=new CommentBibleCandidate({id}),pending=app.signup({email:'one@example.test',username:'member_one',nickname:'첫별',['password']:credential});expectHttp(()=>app.login({username:'member_one',['password']:credential}),401,'invalid_credentials');app.confirm(pending.userId);const session=app.login({username:'member_one',['password']:credential,actor:'ip-a'});assert.equal(app.refresh(session.token).userId,pending.userId);app.logout(session.token);expectHttp(()=>app.refresh(session.token),401,'invalid_session');});
test('회원 글·댓글 CRUD와 타 사용자 격리',()=>{const app=new CommentBibleCandidate({id}),alice=member(app,'alice'),bob=member(app,'bobby');const post=app.createPost({token:alice.token,title:'첫 묵상',content:'본문',idempotencyKey:key(1)}),replay=app.createPost({token:alice.token,title:'첫 묵상',content:'본문',idempotencyKey:key(1)});assert.equal(replay.id,post.id);assert.equal(app.posts.size,1);expectHttp(()=>app.updatePost({token:bob.token,id:post.id,title:'탈취',content:'실패'}),403,'forbidden');assert.equal(app.updatePost({token:alice.token,id:post.id,title:'수정 묵상',content:'수정 본문'}).version,2);const comment=app.createComment({token:bob.token,postId:post.id,content:'댓글',idempotencyKey:key(2)});assert.equal(app.listNotifications(alice.token).length,1);expectHttp(()=>app.deleteComment({token:alice.token,id:comment.id}),403,'forbidden');assert.ok(app.deleteComment({token:bob.token,id:comment.id}).deletedAt);assert.ok(app.deletePost({token:alice.token,id:post.id}).deletedAt);});
test('익명 비밀번호·동일 actor 소유권과 신고 중복 방지',()=>{const app=new CommentBibleCandidate({id}),anonymousId='anonymous_actor_0001',anonymousCredential=['anonymous','pass'].join('-'),wrongCredential=['wrong','pass'].join('-');const post=app.createPost({anonymousId,['password']:anonymousCredential,title:'익명 글',content:'내용',idempotencyKey:key(3)});expectHttp(()=>app.updatePost({anonymousId:'anonymous_actor_0002',['password']:anonymousCredential,id:post.id,title:'탈취',content:'실패'}),403,'forbidden');expectHttp(()=>app.updatePost({anonymousId,['password']:wrongCredential,id:post.id,title:'실패',content:'실패'}),403,'forbidden');assert.equal(app.updatePost({anonymousId,['password']:anonymousCredential,id:post.id,title:'정상 수정',content:'정상'}).title,'정상 수정');const report=app.report({anonymousId,targetType:'post',targetId:post.id,idempotencyKey:key(4)});assert.equal(app.report({anonymousId,targetType:'post',targetId:post.id,idempotencyKey:key(4)}).id,report.id);});
test('절 댓글·회원 기록 RLS와 cursor pagination',()=>{const app=new CommentBibleCandidate({id}),alice=member(app,'markalice'),bob=member(app,'markbobby');app.upsertMark({token:alice.token,verseId:'gen-1-1',bookmark:true,memo:'나만의 메모'});assert.equal(app.listMarks(alice.token).length,1);assert.equal(app.listMarks(bob.token).length,0);for(let i=0;i<7;i++)app.createComment({token:alice.token,verseId:'gen-1-1',content:`댓글 ${i}`,idempotencyKey:key(10+i)});const first=app.listComments({verseId:'gen-1-1',limit:3}),second=app.listComments({verseId:'gen-1-1',limit:3,cursor:first.nextCursor});assert.equal(first.data.length,3);assert.equal(second.data.length,3);assert.equal(new Set([...first.data,...second.data].map(row=>row.id)).size,6);assert.equal(app.listComments({verseId:'gen-1-1',limit:1000}).data.length,7);});
test('rate limit·idempotency payload mismatch·장애 복구',()=>{const app=new CommentBibleCandidate({id,limits:{write:2,windowMs:60_000}}),session=member(app,'limited');app.createPost({token:session.token,title:'글 하나',content:'내용',idempotencyKey:key(30)});app.createPost({token:session.token,title:'글 둘',content:'내용',idempotencyKey:key(31)});expectHttp(()=>app.createPost({token:session.token,title:'글 셋',content:'내용',idempotencyKey:key(32)}),429,'too_many_requests');const separate=new CommentBibleCandidate({id}),actor=member(separate,'retryuser');separate.createPost({token:actor.token,title:'원문',content:'내용',idempotencyKey:key(40)});expectHttp(()=>separate.createPost({token:actor.token,title:'변조',content:'내용',idempotencyKey:key(40)}),409,'idempotency_payload_mismatch');separate.setAvailable(false);expectHttp(()=>separate.listPosts(),503,'temporarily_unavailable');separate.setAvailable(true);assert.equal(separate.listPosts().data.length,1);});
test('optimistic UI commit·rollback과 bounded outbox',()=>{const ui=new OptimisticState([{id:'old',content:'기존'}]);ui.begin({id:'temp-ok',row:{content:'대기'}});assert.equal(ui.rows[0].pending,true);ui.commit('temp-ok',{id:'server-id',content:'저장됨'});assert.equal(ui.rows[0].pending,false);ui.begin({id:'temp-fail',row:{content:'실패 예정'}});ui.rollback('temp-fail');assert.equal(ui.rows.some(row=>row.id==='temp-fail'),false);const app=new CommentBibleCandidate({id});app.enqueue('view',{target:'post:1'},2);app.enqueue('notification',{target:'post:1'},2);expectHttp(()=>app.enqueue('overflow',{},2),503,'outbox_backpressure');assert.equal(app.drainOutbox(100).length,2);});
// 스크립트 끝 — CommentBible 전체 기능 E2E fixture 1.0.0
