// 스크립트 이름: CommentBible 관리자 인사이트 화면
// 버전: 1.0.0
// 작성일: 2026-08-14
// 변경사항: 동적 관리자 검사·집계·필터·cursor·안전 CSV
// 용도: /admin/insights 반응형 운영 대시보드
// 사용자 입력 필요: 관리자 로그인
(()=>{'use strict';
const SUPABASE_URL='https://rayvvlerwxumqvmodvsy.supabase.co',KEY='sb_publishable_k6jRijBWjC4hcEO--pEHEg_zYI7KGUZ',db=window.supabase?.createClient(SUPABASE_URL,KEY);
const $=id=>document.getElementById(id),state={cursor:null,stack:[],page:1,next:null};
const metricLabels={active_now:'지금 접속',visitors_today:'오늘 방문자',visitors_7d:'7일 방문자',visitors_30d:'30일 방문자',sessions:'고유 세션',new_visitors:'신규 방문',returning_visitors:'재방문',pageviews:'페이지뷰',signup:'가입 전환',login:'로그인 전환',post:'글 작성',comment:'댓글 작성',reports:'신고',errors:'오류',rate_429:'429',read_p50:'읽기 p50',read_p95:'읽기 p95',write_p50:'쓰기 p50',write_p95:'쓰기 p95',dropped:'수집 드롭'};
document.addEventListener('DOMContentLoaded',init,{once:true});
async function init(){$('refresh').onclick=load;$('retry').onclick=load;$('range').onchange=load;$('filters').onsubmit=e=>{e.preventDefault();state.cursor=null;state.stack=[];state.page=1;loadVisitors()};$('next').onclick=()=>{state.stack.push(state.cursor);state.cursor=state.next;state.page++;loadVisitors()};$('prev').onclick=()=>{state.cursor=state.stack.pop()??null;state.page=Math.max(1,state.page-1);loadVisitors()};$('exportCsv').onclick=exportCsv;await load()}
async function invoke(body){if(!db)throw Object.assign(new Error('unavailable'),{status:503});const {data:{session}}=await db.auth.getSession();if(!session)throw Object.assign(new Error('unauthorized'),{status:401});const {data,error}=await db.functions.invoke('admin-insights',{body,headers:{Authorization:`Bearer ${session.access_token}`}});if(error){const status=error?.context?.status||500;throw Object.assign(error,{status})}return data}
async function load(){showState('loading');try{const data=await invoke({action:'dashboard',days:Number($('range').value)});render(data);$('state').hidden=true;$('forbidden').hidden=true;$('dashboard').hidden=false;state.cursor=null;state.stack=[];state.page=1;await loadVisitors()}catch(error){if(error.status===401||error.status===403){$('state').hidden=true;$('dashboard').hidden=true;$('forbidden').hidden=false}else showState('error')}}
function showState(mode){$('dashboard').hidden=true;$('forbidden').hidden=true;$('state').hidden=false;$('state').className=`state ${mode}`;$('state').querySelector('strong').textContent=mode==='loading'?'권한과 집계를 확인하는 중입니다.':'인사이트를 불러오지 못했습니다. 본문 기능에는 영향이 없습니다.';$('state').querySelector('.spinner').hidden=mode!=='loading';$('retry').hidden=mode==='loading'}
function render(data){const metrics=data.metrics||{};$('metrics').replaceChildren(...Object.entries(metricLabels).map(([key,label])=>{const el=document.createElement('article');el.className='metric';const value=metrics[key]??0;el.append(node('span',label),node('strong',key.includes('p')&&key.match(/p\d/) ? `${value}ms`:format(value)),node('small',key==='dropped'?'관리자 확인 필요':'집계 구간'));return el}));renderTrend(data.trend||[]);renderFunnel(data.funnel||[]);renderRank('popularBible',data.popular_bible||[]);renderRank('popularPages',data.popular_pages||[]);renderRank('sources',data.sources||[]);$('coarseStats').replaceChildren(...['devices','browsers','countries'].flatMap(key=>(data[key]||[]).map(row=>node('span',`${row.label} ${format(row.count)}`,'chip'))));$('generatedAt').dateTime=data.generated_at||'';$('generatedAt').textContent=date(data.generated_at)}
function renderTrend(rows){const host=$('trendChart');host.replaceChildren();if(!rows.length){host.append(node('p','표시할 추이가 없습니다.','empty'));return}const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),max=Math.max(1,...rows.flatMap(x=>[x.visitors,x.pageviews]));rows.forEach((row,i)=>{const x=20+i*(960/Math.max(1,rows.length-1)),y=225-(row.pageviews/max)*190,c=document.createElementNS(ns,'circle');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r','4');c.setAttribute('fill','#6e2f3d');svg.append(c);const bar=document.createElementNS(ns,'rect');bar.setAttribute('x',x-3);bar.setAttribute('y',225-(row.visitors/max)*190);bar.setAttribute('width','6');bar.setAttribute('height',(row.visitors/max)*190);bar.setAttribute('fill','#386b59');svg.append(bar)});svg.setAttribute('viewBox','0 0 1000 250');host.append(svg)}
function renderFunnel(rows){$('funnel').replaceChildren(...rows.map((row,index)=>{const wrap=node('div','','funnel-row'),base=rows[0]?.count||1;wrap.append(node('span',row.label),node('span','','funnel-bar'),node('strong',`${Math.round(row.count/base*100)}%`));wrap.children[1].style.width=`${Math.max(3,row.count/base*100)}%`;return wrap}))}
function renderRank(id,rows){$(id).replaceChildren(...rows.map(row=>{const li=node('li',row.label);li.append(node('span',format(row.count)));return li}));if(!rows.length)$(id).append(node('li','표시할 데이터가 없습니다.'))}
async function loadVisitors(){try{const data=await invoke({action:'visitors',cursor:state.cursor,limit:25,filters:{from:$('from').value||null,to:$('to').value||null,event:$('event').value||null,source:$('source').value.trim()||null,login:$('login').value}});const rows=data.rows||[];$('visitorRows').replaceChildren(...rows.map(row=>{const tr=document.createElement('tr');[date(row.first_at),`${row.visitor_id} / ${row.session_id}`,row.logged_in?'예':'아니오',row.masked_user,`${row.first_path} → ${row.last_path}`,`${row.pageviews} / ${row.actions}`,row.source,row.device,row.country,date(row.last_at)].forEach((value,i)=>tr.append(node('td',value,i===4?'paths':'')));return tr}));$('visitorEmpty').hidden=rows.length>0;state.next=data.next_cursor||null;$('next').disabled=!state.next;$('prev').disabled=!state.stack.length;$('pageLabel').textContent=`${state.page} 페이지`}catch(error){if(error.status===403)showState('forbidden');else showState('error')}}
async function exportCsv(){const button=$('exportCsv');button.disabled=true;try{const data=await invoke({action:'export',filters:{from:$('from').value||null,to:$('to').value||null,event:$('event').value||null,source:$('source').value.trim()||null,login:$('login').value}});const blob=new Blob([data.csv||''],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='commentbible-insights.csv';a.click();URL.revokeObjectURL(a.href)}finally{button.disabled=false}}
function node(tag,text='',className=''){const el=document.createElement(tag);el.textContent=String(text);if(className)el.className=className;return el}function format(value){return new Intl.NumberFormat('ko-KR').format(Number(value)||0)}function date(value){const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('ko-KR',{dateStyle:'short',timeStyle:'short'}).format(d)}
})();
// 스크립트 끝 — CommentBible 관리자 인사이트 화면 1.0.0
